Repository cham-ggae/Backend, pull requests merged in 2025-06, with the labels that each got.

#3 CHAM-32 FEAT: spring jwt token 생성 및 토큰 검증 기능 추가
  build.gradle
  src/main/java/com/example/demo/login/controller/LoginController.java
  src/main/java/com/example/demo/login/dao/UserDao.java
  src/main/java/com/example/demo/login/dto/User.java
  src/main/java/com/example/demo/login/service/KakaoLogin.java
  src/main/java/com/example/demo/login/service/KakaoLoginService.java
  src/main/java/com/example/demo/provider/JwtFilter.java
  src/main/java/com/example/demo/provider/JwtProvider.java
  src/main/java/com/example/demo/test/TestController.java
  src/main/resources/mapper/User.xml
Labels: enhancement

#13 CHAM-55 STT/TTS API 구현
  .gitignore
  build.gradle
  src/main/java/com/example/demo/voice/controller/VoiceController.java
  src/main/java/com/example/demo/voice/dao/VoiceDao.java
  src/main/java/com/example/demo/voice/dto/TranscribedTextResponse.java
  src/main/java/com/example/demo/voice/dto/TtsLogRequest.java
  src/main/java/com/example/demo/voice/dto/TtsLogResponse.java
  src/main/java/com/example/demo/voice/service/GoogleSttService.java
  src/main/java/com/example/demo/voice/service/GoogleSttServiceImpl.java
  src/main/java/com/example/demo/voice/service/GoogleTtsService.java
  src/main/java/com/example/demo/voice/service/GoogleTtsServiceImpl.java
  src/main/java/com/example/demo/voice/service/VoiceService.java
  src/main/java/com/example/demo/voice/service/VoiceServiceImpl.java
  src/main/resources/mapper/Voice.xml
Labels: enhancement

#10 CHAM-52 새싹 키우기 전체 API 작성
  build.gradle
  src/main/java/com/example/demo/config/SecurityConfig.java
  src/main/java/com/example/demo/config/WebSocketConfig.java
  src/main/java/com/example/demo/plant/controller/NutrientController.java
  src/main/java/com/example/demo/plant/controller/PlantController.java
  src/main/java/com/example/demo/plant/controller/PointController.java
  src/main/java/com/example/demo/plant/dao/NutrientDao.java
  src/main/java/com/example/demo/plant/dao/PlantDao.java
  src/main/java/com/example/demo/plant/dao/PointDao.java
  src/main/java/com/example/demo/plant/dto/AddPointRequestDto.java
  src/main/java/com/example/demo/plant/dto/CreatePlantRequestDto.java
  src/main/java/com/example/demo/plant/dto/PlantStatusResponseDto.java
  src/main/java/com/example/demo/plant/dto/RewardHistoryDto.java
  src/main/java/com/example/demo/plant/exception/PlantExceptions.java
  src/main/java/com/example/demo/plant/service/NutrientService.java
  src/main/java/com/example/demo/plant/service/PlantService.java
  src/main/java/com/example/demo/plant/service/PointService.java
  src/main/java/com/example/demo/plant/websocket/WaterWebSocketHandler.java
  src/main/java/com/example/demo/plant/websocket/dto/WaterEventData.java
  src/main/java/com/example/demo/provider/JwtFilter.java
  src/main/resources/mapper/NutrientMapper.xml
  src/main/resources/mapper/PlantMapper.xml
  src/main/resources/mapper/PointMapper.xml
Labels: feat

#16 CHAM-70 가족 메시지 카드 + 댓글 기능 구현
  .gitignore
  src/main/java/com/example/demo/familycard/controller/FamilyCardCommentController.java
  src/main/java/com/example/demo/familycard/controller/FamilyCardController.java
  src/main/java/com/example/demo/familycard/dao/FamilyCardCommentDao.java
  src/main/java/com/example/demo/familycard/dao/FamilyCardDao.java
  src/main/java/com/example/demo/familycard/dto/CommentListResponse.java
  src/main/java/com/example/demo/familycard/dto/CommentResponse.java
  src/main/java/com/example/demo/familycard/dto/CreateCommentRequest.java
  src/main/java/com/example/demo/familycard/dto/CreateFamilyCardRequest.java
  src/main/java/com/example/demo/familycard/dto/FamilyCard.java
  src/main/java/com/example/demo/familycard/dto/FamilyCardComment.java
  src/main/java/com/example/demo/familycard/dto/FamilyCardListResponse.java
  src/main/java/com/example/demo/familycard/dto/FamilyCardResponse.java
  src/main/java/com/example/demo/familycard/dto/UpdateCommentRequest.java
  src/main/java/com/example/demo/familycard/dto/UpdateFamilyCardRequest.java
  src/main/java/com/example/demo/familycard/enums/MessageCardImageType.java
  src/main/java/com/example/demo/familycard/service/FamilyCardCommentService.java
  src/main/java/com/example/demo/familycard/service/FamilyCardService.java
  src/main/resources/mapper/FamilCardComment.xml
  src/main/resources/mapper/FamilyCard.xml
Labels: feat

#17 CHAM-64 FEAT: 챗봇 이전 대화 기억 기능 구현
  .gitignore
  src/main/java/com/example/demo/chatbot/controller/ChatbotController.java
  src/main/java/com/example/demo/chatbot/dao/ChatbotDao.java
  src/main/java/com/example/demo/chatbot/dto/ChatCompletionChunk.java
  src/main/java/com/example/demo/chatbot/dto/Chatting.java
  src/main/java/com/example/demo/chatbot/service/Chatbot.java
  src/main/java/com/example/demo/chatbot/service/ChatbotService.java
  src/main/resources/mapper/Chatbot.xml
Labels: feat

#18 CHAM-73 회원가입 시 추가정보 필요 분기 처리 / 회원정보 추가 엔드포인트 구현
  src/main/java/com/example/demo/config/SecurityConfig.java
  src/main/java/com/example/demo/familycard/controller/FamilyCardCommentController.java
  src/main/java/com/example/demo/login/controller/LoginController.java
  src/main/java/com/example/demo/login/dao/UserDao.java
  src/main/java/com/example/demo/login/dto/AdditionalUserInfoRequest.java
  src/main/java/com/example/demo/login/service/KakaoLoginService.java
  src/main/java/com/example/demo/login/service/UserService.java
  src/main/resources/mapper/User.xml
Labels: bug, enhancement

#24 CHAM-84 FEAT: 가족 모드 활성화 시 RAG 데이터를 불러옴, requestParam에 가족 구성원의 수 추가
  src/main/java/com/example/demo/chatbot/controller/ChatbotController.java
  src/main/java/com/example/demo/chatbot/dao/ChatbotDao.java
  src/main/java/com/example/demo/chatbot/dto/RagSource.java
  src/main/java/com/example/demo/chatbot/service/Chatbot.java
  src/main/java/com/example/demo/chatbot/service/ChatbotService.java
  src/main/resources/mapper/Chatbot.xml
Labels: enhancement, feat

#29 CHAM-55 STT API sessionId 타입 불일치 해결
  src/main/java/com/example/demo/voice/controller/VoiceController.java
  src/main/java/com/example/demo/voice/service/VoiceService.java
  src/main/java/com/example/demo/voice/service/VoiceServiceImpl.java
Labels: bug

#30 CHAM-97 family recommend 기능 구현 및 family 조회 정보 확장
  src/main/java/com/example/demo/family/controller/FamilyController.java
  src/main/java/com/example/demo/family/dao/FamilyDao.java
  src/main/java/com/example/demo/family/dto/FamilyDashboardResponse.java
  src/main/java/com/example/demo/family/dto/FamilyMember.java
  src/main/java/com/example/demo/family/dto/FamilyMemberSurveyInfo.java
  src/main/java/com/example/demo/family/dto/FamilyPlanRecommendationResponse.java
  src/main/java/com/example/demo/family/service/FamilyPlanRecommendationService.java
  src/main/java/com/example/demo/family/service/FamilyService.java
  src/main/resources/mapper/Family.xml
Labels: enhancement
